version: 2
updates:
  # Docker base images (ubuntu:22.04)
  - package-ecosystem: docker
    directory: /sender
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: docker
    directory: /receiver
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(docker)"

  # GitHub Actions versions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"
