name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    strategy:
      matrix:
        svc: [sender, receiver]
    steps:
      - run: echo "build ${{ matrix.svc }}"
